export default [
  {
    prefix: '@font-face',
    body: '@font-face {\t$1}',
    description: '@font-face',
    values: [
      'font-family: $1;',
      'src: $1;',
      'font-stretch: $1;',
      'font-style: $1;',
      'font-weight: $1;',
      'unicode-range: $1;',
    ],
  },
  {
    prefix: '@import',
    body: '@import "$1";',
    description: '@import "$1";',
  },
  {
    prefix: '@keyframes',
    body: '@keyframes $1 {\t$1}',
    description: '@keyframes',
  },
  {
    prefix: '@media',
    body: '@media ($1) {\t$1}',
    description: '@media',
  },
  {
    prefix: '@supports',
    body: '@supports ($1) {\t$1}',
    description: '@supports',
  },
  {
    prefix: 'align-content',
    body: 'align-content: $1;',
    description: 'align-content: $1;',
    values: [
      'stretch',
      'center',
      'flex-start',
      'flex-end',
      'space-between',
      'space-around',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'align-items',
    body: 'align-items: $1;',
    description: 'align-items: $1;',
    values: [
      'stretch',
      'center',
      'flex-start',
      'flex-end',
      'baseline',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'align-self',
    body: 'align-self: $1;',
    description: 'align-self: $1;',
    values: [
      'auto',
      'stretch',
      'center',
      'flex-start',
      'flex-end',
      'baseline',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'animation',
    body: 'animation: $1;',
    description: 'animation: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'animation-delay',
    body: 'animation-delay: $1;',
    description: 'animation-delay: $1;',
    values: ['$1s', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'animation-direction',
    body: 'animation-direction: $1;',
    description: 'animation-direction: $1;',
    values: [
      'normal',
      'reverse',
      'alternate',
      'alternate-reverse',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'animation-duration',
    body: 'animation-duration: $1;',
    description: 'animation-duration: $1;',
    values: ['$1s', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'animation-fill-mode',
    body: 'animation-fill-mode: $1;',
    description: 'animation-fill-mode: $1;',
    values: ['none', 'forwards', 'backwards', 'both', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'animation-iteration-count',
    body: 'animation-iteration-count: $1;',
    description: 'animation-iteration-count: $1;',
    values: ['infinite', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'animation-name',
    body: 'animation-name: $1;',
    description: 'animation-name: $1;',
    values: ['none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'animation-play-state',
    body: 'animation-play-state: $1;',
    description: 'animation-play-state: $1;',
    values: ['paused', 'running', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'animation-timing-function',
    body: 'animation-timing-function: $1;',
    description: 'animation-timing-function: $1;',
    values: [
      'linear',
      'ease',
      'ease-in',
      'ease-out',
      'ease-in-out',
      'cubic-bezier($1, $2, $3, $4)',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'backface-visibility',
    body: 'backface-visibility: $1;',
    description: 'backface-visibility: $1;',
    values: ['visible', 'hidden', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'background',
    body: 'background: $1;',
    description: 'background: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'background-attachment',
    body: 'background-attachment: $1;',
    description: 'background-attachment: $1;',
    values: ['scroll', 'fixed', 'local', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'background-blend-mode',
    body: 'background-blend-mode: $1;',
    description: 'background-blend-mode: $1;',
    values: [
      'normal',
      'multiply',
      'screen',
      'overlay',
      'darken',
      'lighten',
      'color-dodge',
      'saturation',
      'color',
      'luminosity',
      'unset',
    ],
  },
  {
    prefix: 'background-clip',
    body: 'background-clip: $1;',
    description: 'background-clip: $1;',
    values: ['border-box', 'padding-box', 'content-box', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'background-color',
    body: 'background-color: $1;',
    description: 'background-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'transparent',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'background-image',
    body: 'background-image: $1;',
    description: 'background-image: $1;',
    values: ['url("$1")', 'none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'background-origin',
    body: 'background-origin: $1;',
    description: 'background-origin: $1;',
    values: ['padding-box', 'border-box', 'content-box', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'background-position',
    body: 'background-position: $1;',
    description: 'background-position: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'background-repeat',
    body: 'background-repeat: $1;',
    description: 'background-repeat: $1;',
    values: [
      'repeat',
      'repeat-x',
      'repeat-y',
      'no-repeat',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'background-size',
    body: 'background-size: $1;',
    description: 'background-size: $1;',
    values: ['auto', 'cover', 'contain', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border',
    body: 'border: $1;',
    description: 'border: $1;',
    values: ['$1px ${2:solid} $3', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-bottom',
    body: 'border-bottom: $1;',
    description: 'border-bottom: $1;',
    values: ['$1px ${2:solid} $3', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-bottom-color',
    body: 'border-bottom-color: $1;',
    description: 'border-bottom-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'transparent',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-bottom-left-radius',
    body: 'border-bottom-left-radius: $1;',
    description: 'border-bottom-left-radius: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-bottom-right-radius',
    body: 'border-bottom-right-radius: $1;',
    description: 'border-bottom-right-radius: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-bottom-style',
    body: 'border-bottom-style: $1;',
    description: 'border-bottom-style: $1;',
    values: [
      'none',
      'hidden',
      'dotted',
      'dashed',
      'solid',
      'double',
      'groove',
      'ridge',
      'inset',
      'outset',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-bottom-width',
    body: 'border-bottom-width: $1;',
    description: 'border-bottom-width: $1;',
    values: ['$1px', 'medium', 'thin', 'thick', 'length', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-collapse',
    body: 'border-collapse: $1;',
    description: 'border-collapse: $1;',
    values: ['separate', 'collapse', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-color',
    body: 'border-color: $1;',
    description: 'border-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'transparent',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-image',
    body: 'border-image: $1;',
    description: 'border-image: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-image-outset',
    body: 'border-image-outset: $1;',
    description: 'border-image-outset: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-image-repeat',
    body: 'border-image-repeat: $1;',
    description: 'border-image-repeat: $1;',
    values: ['stretch', 'repeat', 'round', 'space', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-image-slice',
    body: 'border-image-slice: $1;',
    description: 'border-image-slice: $1;',
    values: ['fill', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-image-source',
    body: 'border-image-source: $1;',
    description: 'border-image-source: $1;',
    values: ['none', 'url("$1")', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-image-width',
    body: 'border-image-width: $1;',
    description: 'border-image-width: $1;',
    values: ['auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-left',
    body: 'border-left: $1;',
    description: 'border-left: $1;',
    values: ['$1px ${2:solid} $3', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-left-color',
    body: 'border-left-color: $1;',
    description: 'border-left-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'transparent',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-left-style',
    body: 'border-left-style: $1;',
    description: 'border-left-style: $1;',
    values: [
      'none',
      'hidden',
      'dotted',
      'dashed',
      'solid',
      'double',
      'groove',
      'ridge',
      'inset',
      'outset',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-left-width',
    body: 'border-left-width: $1;',
    description: 'border-left-width: $1;',
    values: ['$1px', 'medium', 'thin', 'thick', 'length', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-radius',
    body: 'border-radius: $1;',
    description: 'border-radius: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-right',
    body: 'border-right: $1;',
    description: 'border-right: $1;',
    values: ['$1px ${2:solid} $3', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-right-color',
    body: 'border-right-color: $1;',
    description: 'border-right-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'transparent',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-right-style',
    body: 'border-right-style: $1;',
    description: 'border-right-style: $1;',
    values: [
      'none',
      'hidden',
      'dotted',
      'dashed',
      'solid',
      'double',
      'groove',
      'ridge',
      'inset',
      'outset',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-right-width',
    body: 'border-right-width: $1;',
    description: 'border-right-width: $1;',
    values: ['$1px', 'medium', 'thin', 'thick', 'length', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-spacing',
    body: 'border-spacing: $1;',
    description: 'border-spacing: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-style',
    body: 'border-style: $1;',
    description: 'border-style: $1;',
    values: [
      'none',
      'hidden',
      'dotted',
      'dashed',
      'solid',
      'double',
      'groove',
      'ridge',
      'inset',
      'outset',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-top',
    body: 'border-top: $1;',
    description: 'border-top: $1;',
    values: ['$1px ${2:solid} $3', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-top-color',
    body: 'border-top-color: $1;',
    description: 'border-top-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'transparent',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-top-left-radius',
    body: 'border-top-left-radius: $1;',
    description: 'border-top-left-radius: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-top-right-radius',
    body: 'border-top-right-radius: $1;',
    description: 'border-top-right-radius: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-top-style',
    body: 'border-top-style: $1;',
    description: 'border-top-style: $1;',
    values: [
      'none',
      'hidden',
      'dotted',
      'dashed',
      'solid',
      'double',
      'groove',
      'ridge',
      'inset',
      'outset',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'border-top-width',
    body: 'border-top-width: $1;',
    description: 'border-top-width: $1;',
    values: ['$1px', 'medium', 'thin', 'thick', 'length', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'border-width',
    body: 'border-width: $1;',
    description: 'border-width: $1;',
    values: ['$1px', 'medium', 'thin', 'thick', 'length', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'bottom',
    body: 'bottom: $1;',
    description: 'bottom: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'box-decoration-break',
    body: 'box-decoration-break: $1;',
    description: 'box-decoration-break: $1;',
    values: ['slice', 'clone', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'box-shadow',
    body: 'box-shadow: $1;',
    description: 'box-shadow: $1;',
    values: ['$1px $2px $3px $4px #$5', 'none', 'inset', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'box-sizing',
    body: 'box-sizing: $1;',
    description: 'box-sizing: $1;',
    values: ['content-box', 'border-box', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'break-after',
    body: 'break-after: $1;',
    description: 'break-after: $1;',
    values: [
      'auto',
      'all',
      'always',
      'avoid',
      'avoid-column',
      'avoid-page',
      'avoid-region',
      'column',
      'left',
      'page',
      'recto',
      'region',
      'right',
      'verso',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'break-before',
    body: 'break-before: $1;',
    description: 'break-before: $1;',
    values: [
      'auto',
      'all',
      'always',
      'avoid',
      'avoid-column',
      'avoid-page',
      'avoid-region',
      'column',
      'left',
      'page',
      'recto',
      'region',
      'right',
      'verso',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'break-inside',
    body: 'break-inside: $1;',
    description: 'break-inside: $1;',
    values: [
      'auto',
      'all',
      'always',
      'avoid',
      'avoid-column',
      'avoid-page',
      'avoid-region',
      'column',
      'left',
      'page',
      'recto',
      'region',
      'right',
      'verso',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'caption-side',
    body: 'caption-side: $1;',
    description: 'caption-side: $1;',
    values: ['top', 'bottom', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'caret-color',
    body: 'caret-color: $1;',
    description: 'caret-color: $1;',
    values: ['#', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'clear',
    body: 'clear: $1;',
    description: 'clear: $1;',
    values: ['none', 'left', 'right', 'both', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'clip',
    body: 'clip: $1;',
    description: 'clip: $1;',
    values: ['rect($1px, $2px, $3px, $4px)', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'color',
    body: 'color: $1;',
    description: 'color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'transparent',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'column-count',
    body: 'column-count: $1;',
    description: 'column-count: $1;',
    values: ['auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'column-fill',
    body: 'column-fill: $1;',
    description: 'column-fill: $1;',
    values: ['balance', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'column-gap',
    body: 'column-gap: $1;',
    description: 'column-gap: $1;',
    values: ['$1px', 'normal', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'column-rule',
    body: 'column-rule: $1;',
    description: 'column-rule: $1;',
    values: ['$1px solid #$2', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'column-rule-color',
    body: 'column-rule-color: $1;',
    description: 'column-rule-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'column-rule-style',
    body: 'column-rule-style: $1;',
    description: 'column-rule-style: $1;',
    values: [
      'none',
      'hidden',
      'dotted',
      'dashed',
      'solid',
      'double',
      'groove',
      'ridge',
      'inset',
      'outset',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'column-rule-width',
    body: 'column-rule-width: $1;',
    description: 'column-rule-width: $1;',
    values: ['$1px', 'medium', 'thin', 'thick', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'column-span',
    body: 'column-span: $1;',
    description: 'column-span: $1;',
    values: ['all', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'column-width',
    body: 'column-width: $1;',
    description: 'column-width: $1;',
    values: ['$1px', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'columns',
    body: 'columns: $1;',
    description: 'columns: $1;',
    values: ['$1px $2', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'content',
    body: 'content: $1;',
    description: 'content: $1;',
    values: [
      '"$1"',
      'normal',
      'none',
      'counter($1)',
      'attr($1)',
      'open-quote',
      'close-quote',
      'no-open-quote',
      'no-close-quote',
      'url($1)',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'counter-increment',
    body: 'counter-increment: $1;',
    description: 'counter-increment: $1;',
    values: ['none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'counter-reset',
    body: 'counter-reset: $1;',
    description: 'counter-reset: $1;',
    values: ['none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'cursor',
    body: 'cursor: $1;',
    description: 'cursor: $1;',
    values: [
      'alias',
      'all-scroll',
      'auto',
      'cell',
      'context-menu',
      'col-resize',
      'copy',
      'crosshair',
      'default',
      'e-resize',
      'ew-resize',
      'grab',
      'grabbing',
      'help',
      'move',
      'n-resize',
      'ne-resize',
      'nesw-resize',
      'ns-resize',
      'nw-resize',
      'nwse-resize',
      'no-drop',
      'none',
      'not-allowed',
      'pointer',
      'progress',
      'row-resize',
      's-resize',
      'se-resize',
      'sw-resize',
      'text',
      'url($1), auto',
      'vertical-text',
      'w-resize',
      'wait',
      'zoom-in',
      'zoom-out',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'direction',
    body: 'direction: $1;',
    description: 'direction: $1;',
    values: ['ltr', 'rtl', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'display',
    body: 'display: $1;',
    description: 'display: $1;',
    values: [
      'inline',
      'block',
      'flex',
      'grid',
      'inline-block',
      'inline-flex',
      'inline-grid',
      'inline-table',
      'list-item',
      'run-in',
      'table',
      'table-caption',
      'table-column-group',
      'table-header-group',
      'table-footer-group',
      'table-row-group',
      'table-cell',
      'table-column',
      'table-row',
      'none',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'empty-cells',
    body: 'empty-cells: $1;',
    description: 'empty-cells: $1;',
    values: ['show', 'hide', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'filter',
    body: 'filter: $1;',
    description: 'filter: $1;',
    values: [
      'blur($1px)',
      'brightness($1%)',
      'contrast($1%)',
      'drop-shadow($1px $2px $3px $4px #$5)',
      'grayscale($1%)',
      'hue-rotate($1deg)',
      'invert($1%)',
      'opacity($1%)',
      'saturate($1%)',
      'sepia($1%)',
      'url($1)',
      'none',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'flex',
    body: 'flex: $1;',
    description: 'flex: $1;',
    values: ['auto', 'initial', 'none', 'inherit', 'unset'],
  },
  {
    prefix: 'flex-basis',
    body: 'flex-basis: $1;',
    description: 'flex-basis: $1;',
    values: ['auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'flex-direction',
    body: 'flex-direction: $1;',
    description: 'flex-direction: $1;',
    values: [
      'column',
      'column-reverse',
      'row',
      'row-reverse',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'flex-flow',
    body: 'flex-flow: $1;',
    description: 'flex-flow: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'flex-grow',
    body: 'flex-grow: $1;',
    description: 'flex-grow: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'flex-shrink',
    body: 'flex-shrink: $1;',
    description: 'flex-shrink: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'flex-wrap',
    body: 'flex-wrap: $1;',
    description: 'flex-wrap: $1;',
    values: ['nowrap', 'wrap', 'wrap-reverse', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'float',
    body: 'float: $1;',
    description: 'float: $1;',
    values: ['none', 'left', 'right', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'font',
    body: 'font: $1;',
    description: 'font: $1;',
    values: [
      '$1 $2px ${3:Arial}, sans-serif',
      'caption',
      'icon',
      'menu',
      'message-box',
      'small-caption',
      'status-bar',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'font-family',
    body: 'font-family: $1;',
    description: 'font-family: $1;',
    values: ['${1:Arial}, sans-serif', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'font-feature-settings',
    body: 'font-feature-settings: $1;',
    description: 'font-feature-settings: $1;',
  },
  {
    prefix: 'font-kerning',
    body: 'font-kerning: $1;',
    description: 'font-kerning: $1;',
    values: ['auto', 'normal', 'none', 'unset'],
  },
  {
    prefix: 'font-size',
    body: 'font-size: $1;',
    description: 'font-size: $1;',
    values: [
      '$1px',
      '$1%',
      'medium',
      'xx-small',
      'x-small',
      'small',
      'large',
      'x-large',
      'xx-large',
      'smaller',
      'larger',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'font-size-adjust',
    body: 'font-size-adjust: $1;',
    description: 'font-size-adjust: $1;',
    values: ['none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'font-stretch',
    body: 'font-stretch: $1;',
    description: 'font-stretch: $1;',
    values: [
      'ultra-condensed',
      'extra-condensed',
      'condensed',
      'semi-condensed',
      'normal',
      'semi-expanded',
      'expanded',
      'extra-expanded',
      'ultra-expanded',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'font-style',
    body: 'font-style: $1;',
    description: 'font-style: $1;',
    values: ['normal', 'italic', 'oblique', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'font-variant',
    body: 'font-variant: $1;',
    description: 'font-variant: $1;',
    values: ['normal', 'small-caps', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'font-variant-caps',
    body: 'font-variant-caps: $1;',
    description: 'font-variant-caps: $1;',
  },
  {
    prefix: 'font-weight',
    body: 'font-weight: $1;',
    description: 'font-weight: $1;',
    values: [
      '100',
      '200',
      '300',
      '400',
      '500',
      '600',
      '700',
      '800',
      '900',
      'normal',
      'bold',
      'bolder',
      'lighter',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'gap',
    body: 'gap: $1;',
    description: 'gap: $1;',
    values: ['$1px', 'unset'],
  },
  {
    prefix: 'grid',
    body: 'grid: $1;',
    description: 'grid: $1;',
    values: ['none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'grid-area',
    body: 'grid-area: $1;',
    description: 'grid-area: $1;',
  },
  {
    prefix: 'grid-auto-columns',
    body: 'grid-auto-columns: $1;',
    description: 'grid-auto-columns: $1;',
    values: [
      '$1px',
      '$1%',
      'minmax($1, $2)',
      'fit-content',
      'max-content',
      'min-content',
      'auto',
      'unset',
    ],
  },
  {
    prefix: 'grid-auto-flow',
    body: 'grid-auto-flow: $1;',
    description: 'grid-auto-flow: $1;',
    values: ['row', 'column', 'dense', 'row dense', 'column dense', 'unset'],
  },
  {
    prefix: 'grid-auto-rows',
    body: 'grid-auto-rows: $1;',
    description: 'grid-auto-rows: $1;',
    values: ['$1px', '$1%', 'max-content', 'min-content', 'auto', 'unset'],
  },
  {
    prefix: 'grid-column',
    body: 'grid-column: $1;',
    description: 'grid-column: $1;',
  },
  {
    prefix: 'grid-column-end',
    body: 'grid-column-end: $1;',
    description: 'grid-column-end: $1;',
    values: ['span $1', 'auto', 'unset'],
  },
  {
    prefix: 'grid-column-gap',
    body: 'grid-column-gap: $1;',
    description: 'grid-column-gap: $1;',
    values: ['$1px', '$1%', 'unset'],
  },
  {
    prefix: 'grid-column-start',
    body: 'grid-column-start: $1;',
    description: 'grid-column-start: $1;',
    values: ['span $1', 'auto', 'unset'],
  },
  {
    prefix: 'grid-row',
    body: 'grid-row: $1;',
    description: 'grid-row: $1;',
  },
  {
    prefix: 'grid-row-end',
    body: 'grid-row-end: $1;',
    description: 'grid-row-end: $1;',
    values: ['span $1', 'auto', 'unset'],
  },
  {
    prefix: 'grid-row-gap',
    body: 'grid-row-gap: $1;',
    description: 'grid-row-gap: $1;',
    values: ['$1px', '$1%', 'unset'],
  },
  {
    prefix: 'grid-row-start',
    body: 'grid-row-start: $1;',
    description: 'grid-row-start: $1;',
    values: ['span $1', 'auto', 'unset'],
  },
  {
    prefix: 'grid-template',
    body: 'grid-template: $1;',
    description: 'grid-template: $1;',
    values: ['none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'grid-template-areas',
    body: 'grid-template-areas: $1;',
    description: 'grid-template-areas: $1;',
    values: ['"$1"', 'none', 'unset'],
  },
  {
    prefix: 'grid-template-columns',
    body: 'grid-template-columns: $1;',
    description: 'grid-template-columns: $1;',
    values: [
      '$1px',
      '$1%',
      'max-content',
      'min-content',
      'none',
      'auto',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'grid-template-rows',
    body: 'grid-template-rows: $1;',
    description: 'grid-template-rows: $1;',
    values: [
      '$1px',
      '$1%',
      'max-content',
      'min-content',
      'none',
      'auto',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'height',
    body: 'height: $1;',
    description: 'height: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'hyphens',
    body: 'hyphens: $1;',
    description: 'hyphens: $1;',
    values: ['none', 'manual', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'isolation',
    body: 'isolation: $1;',
    description: 'isolation: $1;',
    values: ['auto', 'isolate', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'justify-content',
    body: 'justify-content: $1;',
    description: 'justify-content: $1;',
    values: [
      'flex-start',
      'flex-end',
      'center',
      'space-between',
      'space-around',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'left',
    body: 'left: $1;',
    description: 'left: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'letter-spacing',
    body: 'letter-spacing: $1;',
    description: 'letter-spacing: $1;',
    values: ['$1px', 'normal', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'line-height',
    body: 'line-height: $1;',
    description: 'line-height: $1;',
    values: ['$1px', 'normal', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'list-style',
    body: 'list-style: $1;',
    description: 'list-style: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'list-style-image',
    body: 'list-style-image: $1;',
    description: 'list-style-image: $1;',
    values: ['url("$1")', 'none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'list-style-position',
    body: 'list-style-position: $1;',
    description: 'list-style-position: $1;',
    values: ['inside', 'outside', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'list-style-type',
    body: 'list-style-type: $1;',
    description: 'list-style-type: $1;',
    values: [
      'disc',
      'armenian',
      'circle',
      'cjk-ideographic',
      'decimal',
      'decimal-leading-zero',
      'georgian',
      'hebrew',
      'hiragana',
      'hiragana-iroha',
      'katakana',
      'katakana-iroha',
      'lower-alpha',
      'lower-greek',
      'lower-latin',
      'lower-roman',
      'none',
      'square',
      'upper-alpha',
      'upper-latin',
      'upper-roman',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'margin',
    body: 'margin: $1;',
    description: 'margin: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'margin-bottom',
    body: 'margin-bottom: $1;',
    description: 'margin-bottom: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'margin-left',
    body: 'margin-left: $1;',
    description: 'margin-left: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'margin-right',
    body: 'margin-right: $1;',
    description: 'margin-right: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'margin-top',
    body: 'margin-top: $1;',
    description: 'margin-top: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'max-height',
    body: 'max-height: $1;',
    description: 'max-height: $1;',
    values: ['$1px', '$1%', 'none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'max-width',
    body: 'max-width: $1;',
    description: 'max-width: $1;',
    values: ['$1px', '$1%', 'none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'min-height',
    body: 'min-height: $1;',
    description: 'min-height: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'min-width',
    body: 'min-width: $1;',
    description: 'min-width: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'object-fit',
    body: 'object-fit: $1;',
    description: 'object-fit: $1;',
    values: [
      'fill',
      'contain',
      'cover',
      'scale-down',
      'none',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'object-position',
    body: 'object-position: $1;',
    description: 'object-position: $1;',
    value: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'opacity',
    body: 'opacity: $1;',
    description: 'opacity: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'order',
    body: 'order: $1;',
    description: 'order: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'outline',
    body: 'outline: $1;',
    description: 'outline: $1;',
    values: ['$1px solid #$2', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'outline-color',
    body: 'outline-color: $1;',
    description: 'outline-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'invert',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'outline-offset',
    body: 'outline-offset: $1;',
    description: 'outline-offset: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'outline-style',
    body: 'outline-style: $1;',
    description: 'outline-style: $1;',
    values: [
      'none',
      'hidden',
      'dotted',
      'dashed',
      'solid',
      'double',
      'groove',
      'ridge',
      'inset',
      'outset',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'outline-width',
    body: 'outline-width: $1;',
    description: 'outline-width: $1;',
    values: ['$1px', 'medium', 'thin', 'thick', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'overflow',
    body: 'overflow : $1;',
    description: 'overflow : $1;',
    values: ['visible', 'hidden', 'scroll', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'overflow-x',
    body: 'overflow-x: $1;',
    description: 'overflow-x: $1;',
    values: ['visible', 'hidden', 'scroll', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'overflow-y',
    body: 'overflow-y: $1;',
    description: 'overflow-y: $1;',
    values: ['visible', 'hidden', 'scroll', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'padding',
    body: 'padding: $1;',
    description: 'padding: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'padding-bottom',
    body: 'padding-bottom: $1;',
    description: 'padding-bottom: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'padding-left',
    body: 'padding-left: $1;',
    description: 'padding-left: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'padding-right',
    body: 'padding-right: $1;',
    description: 'padding-right: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'padding-top',
    body: 'padding-top: $1;',
    description: 'padding-top: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'page-break-after',
    body: 'page-break-after: $1;',
    description: 'page-break-after: $1;',
    values: ['auto', 'always', 'avoid', 'left', 'right', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'page-break-before',
    body: 'page-break-before: $1;',
    description: 'page-break-before: $1;',
    values: ['auto', 'always', 'avoid', 'left', 'right', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'page-break-inside',
    body: 'page-break-inside: $1;',
    description: 'page-break-inside: $1;',
    values: ['auto', 'avoid', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'perspective',
    body: 'perspective: $1;',
    description: 'perspective: $1;',
    values: ['$1px', 'none', 'unset'],
  },
  {
    prefix: 'perspective-origin',
    body: 'perspective-origin: $1;',
    description: 'perspective-origin: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'pointer-events',
    body: 'pointer-events: $1;',
    description: 'pointer-events: $1;',
    values: ['auto', 'none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'position',
    body: 'position: $1;',
    description: 'position: $1;',
    values: [
      'relative',
      'absolute',
      'fixed',
      'sticky',
      'static',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'quotes',
    body: 'quotes: $1;',
    description: 'quotes: $1;',
    values: [
      'none',
      'initial',
      'inherit',
      '"',
      "'",
      '‹',
      '›',
      '«',
      '»',
      '‘',
      '’',
      '“',
      '”',
      '„',
      'unset',
    ],
  },
  {
    prefix: 'resize',
    body: 'resize: $1;',
    description: 'resize: $1;',
    values: ['none', 'both', 'horizontal', 'vertical', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'right',
    body: 'right: $1;',
    description: 'right: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'row-gap',
    body: 'row-gap: $1;',
    description: 'row-gap: $1;',
    values: ['$1px', 'normal', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'scroll-behavior',
    body: 'scroll-behavior: $1;',
    description: 'scroll-behavior: $1;',
    values: ['auto', 'smooth', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'tab-size',
    body: 'tab-size: $1;',
    description: 'tab-size: $1;',
    values: ['initial', 'inherit', 'unset'],
  },
  {
    prefix: 'table-layout',
    body: 'table-layout: $1;',
    description: 'table-layout: $1;',
    values: ['auto', 'fixed', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'text-align',
    body: 'text-align: $1;',
    description: 'text-align: $1;',
    values: ['left', 'right', 'center', 'justify', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'text-align-last',
    body: 'text-align-last: $1;',
    description: 'text-align-last: $1;',
    values: [
      'auto',
      'left',
      'right',
      'center',
      'justify',
      'start',
      'end',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'text-decoration',
    body: 'text-decoration: $1;',
    description: 'text-decoration: $1;',
    values: [
      'none',
      'underline',
      'overline',
      'line-through',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'text-decoration-color',
    body: 'text-decoration-color: $1;',
    description: 'text-decoration-color: $1;',
    values: [
      '#',
      'rgb($1, $2, $3)',
      'rgba($1, $2, $3, $4)',
      'hsl($1, $2, $3)',
      'hsla($1, $2, $3, $4)',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'text-decoration-line',
    body: 'text-decoration-line: $1;',
    description: 'text-decoration-line: $1;',
    values: [
      'none',
      'underline',
      'overline',
      'line-through',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'text-decoration-style',
    body: 'text-decoration-style: $1;',
    description: 'text-decoration-style: $1;',
    values: [
      'solid',
      'double',
      'dotted',
      'dashed',
      'wavy',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'text-indent',
    body: 'text-indent: $1;',
    description: 'text-indent: $1;',
    values: ['$1px', '$1%', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'text-justify',
    body: 'text-justify: $1;',
    description: 'text-justify: $1;',
    values: [
      'auto',
      'inter-word',
      'inter-ideograph',
      'inter-cluster',
      'distribute',
      'kashida',
      'trim',
      'none',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'text-orientation',
    body: 'text-orientation: $1;',
    description: 'text-orientation: $1;',
    values: [
      'mixed',
      'upright',
      'sideways',
      'sideways-right',
      'use-glyph-orientation',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'text-overflow',
    body: 'text-overflow: $1;',
    description: 'text-overflow: $1;',
    values: ['ellipsis', 'clip', '"$1"', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'text-shadow',
    body: 'text-shadow: $1;',
    description: 'text-shadow: $1;',
    values: ['$1px $2px $3px #$5', 'none', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'text-transform',
    body: 'text-transform: $1;',
    description: 'text-transform: $1;',
    values: [
      'none',
      'capitalize',
      'uppercase',
      'lowercase',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'text-underline-position',
    body: 'text-underline-position: $1;',
    description: 'text-underline-position: $1;',
  },
  {
    prefix: 'top',
    body: 'top: $1;',
    description: 'top: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'transform',
    body: 'transform: $1;',
    description: 'transform: $1;',
    values: [
      'none',
      'matrix($1, $2, $3, $4, $5, $6)',
      'matrix3d($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)',
      'translate($1, $2)',
      'translate3d($1, $2, $3)',
      'translateX($1)',
      'translateY($1)',
      'translateZ($1)',
      'scale($1, $2)',
      'scale3d($1, $2, $3)',
      'scaleX($1)',
      'scaleY($1)',
      'scaleZ($1)',
      'rotate($1deg)',
      'rotate3d($1, $2, $3, $4deg)',
      'rotateX($1deg)',
      'rotateY($1deg)',
      'rotateZ($1deg)',
      'skew($1deg, $1deg)',
      'skewX($1deg)',
      'skewY($1deg)',
      'perspective($1)',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'transform-origin',
    body: 'transform-origin: $1;',
    description: 'transform-origin: $1;',
    values: [
      'top',
      'left',
      'center',
      'right',
      'bottom',
      '$1px',
      '$1%',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'transform-style',
    body: 'transform-style: $1;',
    description: 'transform-style: $1;',
    values: ['flat', 'preserve-3d', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'transition',
    body: 'transition: $1;',
    description: 'transition: $1;',
    values: ['$1 0.15s', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'transition-delay',
    body: 'transition-delay: $1;',
    description: 'transition-delay: $1;',
    values: ['$1s', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'transition-duration',
    body: 'transition-duration: $1;',
    description: 'transition-duration: $1;',
    values: ['$1s', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'transition-property',
    body: 'transition-property: $1;',
    description: 'transition-property: $1;',
    values: ['none', 'all', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'transition-timing-function',
    body: 'transition-timing-function: $1;',
    description: 'transition-timing-function: $1;',
    values: [
      'ease',
      'linear',
      'ease-in',
      'ease-out',
      'ease-in-out',
      'cubic-bezier($1, $2, $3, $4)',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'unicode-bidi',
    body: 'unicode-bidi: $1;',
    description: 'unicode-bidi: $1;',
    values: ['normal', 'embed', 'bidi-override', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'user-select',
    body: 'user-select: $1;',
    description: 'user-select: $1;',
    values: ['auto', 'none', 'text', 'all', 'unset'],
  },
  {
    prefix: 'vertical-align',
    body: 'vertical-align: $1;',
    description: 'vertical-align: $1;',
    values: [
      'baseline',
      '$1px',
      '$1%',
      'sub',
      'super',
      'top',
      'text-top',
      'middle',
      'bottom',
      'text-bottom',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'visibility',
    body: 'visibility: $1;',
    description: 'visibility: $1;',
    values: ['visible', 'hidden', 'collapse', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'white-space',
    body: 'white-space: $1;',
    description: 'white-space: $1;',
    values: [
      'normal',
      'nowrap',
      'pre',
      'pre-line',
      'pre-wrap',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'width',
    body: 'width: $1;',
    description: 'width: $1;',
    values: ['$1px', '$1%', 'auto', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'word-break',
    body: 'word-break: $1;',
    description: 'word-break: $1;',
    values: [
      'normal',
      'break-all',
      'keep-all',
      'break-word',
      'initial',
      'inherit',
      'unset',
    ],
  },
  {
    prefix: 'word-spacing',
    body: 'word-spacing: $1;',
    description: 'word-spacing: $1;',
    values: ['$1px', 'normal', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'word-wrap',
    body: 'word-wrap: $1;',
    description: 'word-wrap: $1;',
    values: ['normal', 'break-word', 'initial', 'inherit', 'unset'],
  },
  {
    prefix: 'writing-mode',
    body: 'writing-mode: $1;',
    description: 'writing-mode: $1;',
    values: ['horizontal-tb', 'vertical-rl', 'vertical-lr', 'unset'],
  },
  {
    prefix: 'z-index',
    body: 'z-index: $1;',
    description: 'z-index: $1;',
    values: ['auto', 'initial', 'inherit', 'unset'],
  },
]
